### ISSUE TITLE
Fix Image crop and path 

### ISSUE THREAD

**Issue by rjmangubat23** [idpass/smartscanner-core#10]
## TODOs:

- [x] Fix the image resolution from the response via MRZ/Barcode scan
- [x] Fix the image resolution from the response via Manual Capture 
- [x]  Fix image path issues which make the image not properly loaded when used in plugins

**Comment by elahonoridez** [comment]
Tests run on 08 January 2021 at 5:50 PM PH timezone

**VERIFICATION:**
- Able to install the App with the test build **_idpass-smartscanner-debug-2000_01082021_1640.apk_**
- Able to open or use the **MRZ Code** feature
- Able to capture the MRZ code in the sample passport and results with data were loaded in the page.
- Run stress testing by repeating steps 2 to 3 for 30 times.
Used sample passport and its results page shown in the image below:

<img src="https://user-images.githubusercontent.com/75471103/104002317-c77b6900-5205-11eb-968d-318c3541dad6.png" width="300" height="600">

**VALIDATION:**
No issues encountered so far. 

Noting that I've noticed while trying to capture the code, it takes at least 3 seconds before the results appear on the screen. There were also times that it takes more than this.
